version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - backend
  ticket:
    container_name: ticket
    build: ../ticket/
    ports: 
      - 4001:4001
    networks:
      - backend
  packinglot:
    container_name: packinglot
    build: ../parking/
    networks:
      - backend
    ports: 
      - 4002:4002
networks:
   backend:

